# Numpy

In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## Numpy Arrays(ndarray) 

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [12]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [13]:
type(matrix[0][0])

numpy.complex128

In [14]:
type(1)

int

In [15]:
ndarray = np.array([1, 2, 3], dtype=np.uint8) # unsigned + - integer 8bit

In [17]:
ndarray = np.array([1, 2, 3], dtype=np.float32) 

In [19]:
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [22]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
array1 +array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
# 普通のリストは要素ごとの演算ができない
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [37]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [38]:
array1

array([1, 2, 3])

In [39]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
array1 + array2
# Broadcasting 要素が一致しなくても自動で補う
# 行や列が足りない場合でもndarrayの場合はbroadcastingされる。

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [41]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [42]:
ndarray + 3
#broadcastingされる

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Shape

In [47]:
ndarray = np.array([[1, 7], [2, 4], [5, 6]])

In [48]:
ndarray

array([[1, 7],
       [2, 4],
       [5, 6]])

In [49]:
ndarray.shape # .shapeでndarrayの行と列の数を確認できる

(3, 2)

In [50]:
ndarray.reshape(2, 3)

array([[1, 7, 2],
       [4, 5, 6]])

In [51]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [55]:
print(ndarray1.shape)

(3,)


In [56]:
print(ndarray2.shape)

(1, 3)


In [59]:
expand_ndarray = np.expand_dims(ndarray1, axis=1)

In [60]:
expand_ndarray.shape

(3, 1)

In [61]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [64]:
ndarray = np.array([[1, 2, 3], [4, 5 , 6], [7, 8, 9]])

In [65]:
ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
ndarray.flatten() # .flatten: arrayを一次元にする

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## IndexingとSlicing

In [68]:
ndarray = np.array([1, 2, 3, 4])

In [69]:
ndarray

array([1, 2, 3, 4])

In [71]:
ndarray[-1]

4

In [72]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])

In [73]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
ndarray.shape

(3, 2)

In [77]:
ndarray[0, 1]

2

In [78]:
ndarray = np.array([1, 2, 3, 4])

In [79]:
ndarray

array([1, 2, 3, 4])

In [80]:
ndarray[1:3]

array([2, 3])

In [81]:
ndarray[:3]

array([1, 2, 3])

In [82]:
ndarray[1:]

array([2, 3, 4])

In [85]:
ndarray[:-2]

array([1, 2])

In [86]:
ndarray[:]

array([1, 2, 3, 4])

In [88]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
ndarray[:3, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [91]:
ndarray[:3][2:]

array([[ 9, 10, 11, 12]])

In [92]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
ndarray[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [94]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
shape = (5, 4)
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [99]:
np.ones(4)

array([1., 1., 1., 1.])

In [101]:
ndarray = np.ones((5, 4))

In [103]:
ndarray * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [104]:
# 単位行列 I （identify matrix）
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## np.rando.~~ で乱数を生成する

In [113]:
## 擬似乱数　pseudo random
np.random.rand(3, 4)

array([[0.02217683, 0.1615317 , 0.49155129, 0.66821608],
       [0.07976457, 0.65708259, 0.03685568, 0.8159091 ],
       [0.57318789, 0.2267695 , 0.62142672, 0.86027273]])

In [117]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [121]:
np.random.rand()

0.14675589081711304

In [140]:
np.random.randn(3, 4)

array([[ 0.03203253,  0.19627021,  0.90745116, -2.13483482],
       [ 0.81684718,  1.18417131, -0.20448056, -0.11084446],
       [ 1.41448273, -1.416645  ,  0.67351346, -0.77229442]])

In [142]:
np.random.normal(0, 1)

-0.16977402325175425

In [152]:
np.random.randint(10, 100, (2, 3))

array([[47, 32, 64],
       [86, 22, 69]])

In [160]:
a = [1, 2, 3]
np.random.choice(a)

2

In [164]:
index_pool = np.arange(0, 10, 2)
index_pool

array([0, 2, 4, 6, 8])

In [174]:
idx = np.random.choice(index_pool)