In [1]:
3

3

1.3

In [2]:
type(3)

int

In [3]:
type(3/23)

float

In [7]:
type(3.14j)

complex

In [8]:
a == a

NameError: name 'a' is not defined

In [9]:
3 == 3

True

In [11]:
1 == 1.0

True

In [12]:
clear

In [13]:
1e-3

0.001

## String

In [15]:
'single quotations'

'single quotations'

In [16]:
'''
mfasdfa
asdfasd
'''

'\nmfasdfa\nasdfasd\n'

In [17]:
'hello'[0]

'h'

In [18]:
'abcdef'[1:3]

'bc'

In [21]:
'icon.png'[:4]

'icon'

In [23]:
'icon.png'[-3]

'p'

In [25]:
'icon.png'[:-4]

'icon'

In [27]:
'hello{}'.format('world')

'helloworld'

In [30]:
'{firstname} {secondname}'.format(firstname='a',secondname='b')

'a b'

In [31]:
'hello' + 'world'

'helloworld'

In [33]:
date = '20201023'
id = '1'
file_name = date + '_' + id + '.csv'
file_name

'20201023_1.csv'

In [35]:
file_name = '{}_{}.csv'.format(date, id)
file_name

'20201023_1.csv'

In [36]:
'hello world'.split(' ')

['hello', 'world']

In [37]:
'hello world'.split('o')

['hell', ' w', 'rld']

In [38]:
file_name

'20201023_1.csv'

In [39]:
file_name.split('.')

['20201023_1', 'csv']

In [40]:
's'.join(['hello', 'world'])

'hellosworld'

## List

In [44]:
list1 = [1, 'hello', 3]
list1

[1, 'hello', 3]

In [46]:
list1[1]

'hello'

In [48]:
list1.append([1, 1])

In [49]:
list1

[1, 'hello', 3, [1, 1]]

In [51]:
list1[2]

3

In [52]:
[1, 2, 3] + [4, 5]

[1, 2, 3, 4, 5]

## Dictionary

In [56]:
dict1 = {'key1': 'value1', 'key2': 'value2'}
dict1

{'key1': 'value1', 'key2': 'value2'}

In [57]:
dict1.keys()

dict_keys(['key1', 'key2'])

In [58]:
dict1.values()

dict_values(['value1', 'value2'])

## Casting

In [59]:
int(1.0)

1

In [60]:
list('hello')

['h', 'e', 'l', 'l', 'o']

In [61]:
bool(1)

True

In [62]:
bool(2)

True

In [63]:
bool(0)

False

In [64]:
{1, 2, 3, 2, 3, 2,1}

{1, 2, 3}

In [65]:
set([1,2,3,2,1,])

{1, 2, 3}

## 演算子

In [2]:
1 + 1

2

In [3]:
2 - 1

1

In [4]:
2 / 5

0.4

In [5]:
2 ** 3

8

In [7]:
4 // 1

4

In [8]:
16 % 5

1

In [9]:
i = 0

In [10]:
i

0

In [11]:
i = 2

In [12]:
i

2

In [13]:
i = i + 1

In [14]:
i

3

In [20]:
i += 1

In [21]:
i

7

In [22]:
i -= 3

In [23]:
i

4

In [24]:
3 > 1

True

In [25]:
3 < 1

False

In [26]:
3 < 3

False

In [27]:
3 <= 4

True

In [28]:
3 == 3

True

In [29]:
3 == 4

False

In [30]:
3 != 3

False

In [32]:
3 != 4

True

In [33]:
'h' in 'hello'

True

In [35]:
'w' in 'hello'

False

In [36]:
'w' in ['e', 'r', 'w']

True

In [37]:
True and True

True

In [38]:
True and False

False

In [39]:
False and False

False

In [40]:
True or True

True

In [41]:
True or False

True

In [42]:
False or False

False

In [43]:
(4 > 2) and (1 > 3)

False

In [44]:
b

NameError: name 'b' is not defined

In [48]:
a = 1
(a == 1) or (b == 1)
## すでに演算子の前の時点で結果が決まる場合後ろは計算されない。

True

In [49]:
a = [1, 2]
b = [1, 2]

In [50]:
a

[1, 2]

In [51]:
b

[1, 2]

In [52]:
a == b

True

In [54]:
a is b
## オブジェクトが同じかどうかを評価する（==よりも厳密という感じ）

False

In [55]:
a is not b

True

In [56]:
id(a)

139777418618672

In [57]:
id(b)

139777829469872

In [58]:
None

In [59]:
a = None

In [61]:
a is None

True

In [62]:
a

In [63]:
c

NameError: name 'c' is not defined

## if文

In [64]:
a = 1

In [76]:
if a == 2:
    print('a is 2')
elif a <= 0:
    print('a is less than and equal to 0')
else:
    print('a is something else')

a is something else


In [77]:
print('a is 2') if a == 2 else print('a is NOT 2') 
# １行で書くときはelse が必要

a is NOT 2


## Loop処理

### for文

In [84]:
colors = ['red', 'blue', 'green', 'yellow', 'white']
favorite_color = 'blue'
for color in colors:
    if color == favorite_color:
        print('{} is my favorite'.format(color))
    else:
        print('{} is NOT my favorite'.format(color))        

red is NOT my favorite
blue is my favorite
green is NOT my favorite
yellow is NOT my favorite
white is NOT my favorite


In [88]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [89]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [90]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [111]:
for idx, color in enumerate(colors):
    favorite_color = 'blue'
    if color == favorite_color:
        continue # 以降の処理をせずに次のループに移動する
        print('{}: {} is my favorite'.format(idx, color))
    else:
        print('{}: {} is NOT my favorite'.format(idx, color))        

0: red is NOT my favorite
2: green is NOT my favorite
3: yellow is NOT my favorite
4: white is NOT my favorite


### リスト内表記 (List Comprehensions)

In [97]:
colors = ['red', 'blue', 'green', 'yellow', 'white']
colors_png = ['red.png', 'blue.png', 'green.png', 'yellow.png', 'white.png']

result =[]
for color in colors:
    result.append(color + '.png')

print(result)
print(result == colors_png)

['red.png', 'blue.png', 'green.png', 'yellow.png', 'white.png']
True


In [106]:
colors_png = []
for color in colors:
    color_png = color + '.png'
    colors_png.append(color_png)
print(colors_png)

['red.png', 'blue.png', 'green.png', 'yellow.png', 'white.png']


In [103]:
## for文で新しいリストを作成したい時はリスト内包表記を使用した方が速い

In [104]:
[color + '.png' for color in colors]

['red.png', 'blue.png', 'green.png', 'yellow.png', 'white.png']

## while文

In [107]:
i = 0
while i < 5:
    print('{} is less than 5'.format(i))
    i += 1

0 is less than 5
1 is less than 5
2 is less than 5
3 is less than 5
4 is less than 5


In [137]:
r = range(10)

In [140]:
r

range(0, 10)

In [141]:
iter(r)

In [142]:
r_i = iter(r)

In [143]:
next(r_i)

0

In [136]:
list(r)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [112]:
colors = ['red', 'blue', 'green', 'yellow', 'white']
for color in colors:
    print(color)

red
blue
green
yellow
white


In [120]:
colors_i = iter(colors)

In [123]:
next(colors_i)

'green'

In [144]:
iter(colors_i)

In [146]:
# iterableはiter()関数でiteratorを返すオブジェクト
# iteratorはnext()関数でitetationできるオブジェクト
# iteratorそのものもiterable

## 関数

In [182]:
def function(param1, param2="hello"):
    """
    コメント文
    """
    print('Do something for {} and {}'.format(param1, param2))

In [183]:
arg1 = 'argument1'
arg2 = 'argument2'

function(arg1, arg2)
print('hello')

Do something for argument1 and argument2
hello


In [184]:
value = _

In [185]:
value

True

In [186]:
p_r = print('hello world')

hello world


In [187]:
p_r

In [188]:
p_r is None
# その関数に戻り値がない場合、Noneを返す

True

In [189]:
ret = function('a', 'b')

Do something for a and b


In [190]:
ret

In [191]:
ret is None

True

In [196]:
function('o')

Do something for o and hello


## MutableとImmutable 

In [213]:
list_a = [1, 2, 3]

In [214]:
id(list_a)

139777413557296

In [215]:
list_a.append(4)

In [216]:
list_a

[1, 2, 3, 4]

In [217]:
id(list_a)

139777413557296

In [220]:
a = 3
print(id(a))
a += 4
print(a)
print(id(a))

94400934859584
7
94400934859712


In [231]:
list_a = [1, 2, 3]
def append_elem(raw, elem):
    raw.append(elem)
    return raw
# [1, 2, 3, 4]
# 参照渡し（値を渡すというよりメモリの場所を渡しているイメージ）
list_b = append_elem(list_a, elem=4)
list_b

[1, 2, 3, 4]

In [232]:
list_a #list_aはいじっていないので[1,2,3]になると思ったが、これは参照渡しされているのでlist_bと同じ結果になる。

[1, 2, 3, 4]

In [242]:
num_a = 4
# num_b=7
num_b = add_num(num_a, num=3)

In [241]:
def add_num(raw_num, num):
    raw_num += num
    return raw_num

In [243]:
num_b

7

In [244]:
num_a

4

* intergerはimmutableなのでnum_aとnum_bは別のメモリに保存される。
* Pythonの関数は基本的に参照渡し（値を渡すのではなく、その値が入っているメモリの場所を渡す）だがそのオブジェクトはimmutableの場合は値渡しのような挙動をする。

In [246]:
def print_id(param):
    print(id(param))

In [249]:
a = 5
print(id(a))
print_id(a)

94400934859648
94400934859648


## Lambda関数

In [250]:
def func(a):
    return a + 1

In [251]:
x = lambda a: a + 1

In [252]:
func(3)

4

In [253]:
x(3)

4

In [254]:
'image1'
'/home/user/Desktop/image1.jpg'

'/home/user/Desktop/image1.jpg'

In [262]:
def get_filename(path):
    return path.split('/')[-1].split('.')[0]

In [260]:
'/home/user/Desktop/image1.jpg'.split('/')[-1].split('.')[0]

'image1'

In [263]:
get_filename('/home/user/Desktop/image1.jpg')

'image1'

In [266]:
x = lambda path: path.split('/')[-1].split('.')[0]

In [292]:
x('/home/user/Desktop/image1.jpg')

'image1'

In [293]:
filename_list = ['filename1', 'filename2', 'filename3']

In [294]:
[filename + '.png' for filename in filename_list]

['filename1.png', 'filename2.png', 'filename3.png']

In [311]:
def add_extension(filename_list, extension='.png'):
    """
    各要素に'_<その要素のindex番号>.png'をつけたリストを返す
    
    Parameters
    ---------------------------
        filename_list: ファイル名のリスト
    
    Return
    ----------------------------
        filename_png: filename_listの各要素に'_<その要素のindex番号>.png'をつけたリスト
    """
#     filename_png = []
#     for (idx, filename) in enumerate(filename_list):
# #         filename_png.append(filename + '_' + str(idx) + '.png')
#         filename_png.append('[{}_{}.png'.format(filename, idx))
    filename_png = ['{}_{}{}'.format(filename, idx, extension) for idx, filename in enumerate(filename_list)]
    return filename_png

In [312]:
x = lambda filename_list, extension='.png': ['{}_{}{}'.format(filename, idx, extension) for idx, filename in enumerate(filename_list)]

In [315]:
x(filename_list)
# Lambda 関数は表計算をするときによく使う

['filename1_0.png', 'filename2_1.png', 'filename3_2.png']

In [314]:
add_extension(filename_list, '.jpeg')

['filename1_0.jpeg', 'filename2_1.jpeg', 'filename3_2.jpeg']

## *argsと**kwargs

In [317]:
# argsとは「argument」のこと
# kwargsとは「keywordのargumant」のこと

In [318]:
# *argsはいくつでも引数を受け取れる（tupleで入る）

In [330]:
def func1(a, b):
    return a + b

In [350]:
def return_only_png(*args):
    
    png_list = []
    
    for filename in args:
        if filename[-4:] == '.png':
            png_list.append(filename)
    print(type(args))
    return png_list

In [351]:
return_only_png('image1.png', 'image2.jpg')

<class 'tuple'>


['image1.png']

In [352]:
# **kwargsはdictionaryで入る

In [360]:
def print_dict(**kwargs):
    param_a = kwargs.get('a', 100)
    print(param_a)

In [361]:
print_dict(b=2)

100


In [363]:
a = [1, 2, 3, 4]
print(a)
print(*a)
# *をつけるとaをunpackした状態でprint関数に渡す

[1, 2, 3, 4]
1 2 3 4


In [394]:
list_a = [1, 3, 5]
list_b = [2, 4, 6, 8, 10]
list_a_b = [*list_a, *list_b]

In [395]:
list_a_b

[1, 3, 5, 2, 4, 6, 8, 10]

In [396]:
dict_a = {'one': 1, 'two': 2}
dict_b = {'three': 3, 'four': 4, 'five': 5}
dict_a_b = {**dict_a, **dict_b}

In [397]:
dict_a_b

{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5}

In [398]:
def func(a, b):
    return a+10, b+3

In [402]:
x, y = func(3, 5)

In [403]:
x

13

In [404]:
y

8

In [405]:
type(3)

int

In [406]:
type('hello')

str

In [407]:
type(3.2)

float

In [408]:
type(True)

bool

In [412]:
'hello'[3:4]

'l'

In [413]:
print('{}_{}'.format('and', '.png'))

and_.png


In [415]:
4 // 3

1

In [416]:
colors = ['red', 'blue', 'green', 'yellow']
# リスト内包表記
['{}_{}'.format(color, 'hello') for color in colors]

['red_hello', 'blue_hello', 'green_hello', 'yellow_hello']

### iterable
* String
* List
* Tuple
* Set
* Dict

### Not Iterable
* Integer
* Float
* Boolean

=================================

### mutable
#### 一回定義してから最後変更できるオブジェクト
* List
* Set
* Dictionary

### immutable
#### 一回定義するともう変更できない
* Integer
* Float
* Boolean
* String
* Tuple

In [419]:
def append_elem(list_param, elem=0):
    list_param.append(elem)
    return list_param

list_a = [1, 2, 3]
list_b = append_elem(list_a, elem=4)
print('list_a: {}'.format(list_a))
print('list_b: {}'.format(list_b))
# 参照渡しされている

list_a: [1, 2, 3, 4]
list_b: [1, 2, 3, 4]


In [420]:
print(id(list_a))
print(id(list_b))

139777407342384
139777407342384


In [426]:
import numpy as np
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [428]:
list(range(2, 15))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [430]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [431]:
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [434]:
np.linspace(0, 3, 10, endpoint=False)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [433]:
10 ** 0.333333333333

2.1544346900302305

In [ ]:
# np.arange()
# np.linspace()
# np.logspace()